services:
  iqps-backend:
    image: iqps-backend
    build: .
    restart: always
    networks:
      metaploy-network:
        aliases:
          - iqps-backend
      metaploy-private-network:
    volumes:
      - ./db:/db
      - nginx-config-volume:/etc/nginx/sites-enabled
      - odins-vault:/srv/static
    environment:
      - STATIC_FILES_URL=${STATIC_FILES_URL}
      - STATIC_FILES_STORAGE_LOCATION=${STATIC_FILES_STORAGE_LOCATION}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - UPLOADED_QPS_PATH=${UPLOADED_QPS_PATH}

networks:
  metaploy-network:
    external: true
    name: metaploy-network
  metaploy-private-network:
    external: true
    name: metaploy-private-network

volumes:
  nginx-config-volume:
    external: true
    name: metaploy-nginx-config-volume
  odins-vault:
    external: true
    name: odins-vault
